<?php
/**
 * MdSettingsDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Memsource\Model;

use \ArrayAccess;
use \Memsource\ObjectSerializer;

/**
 * MdSettingsDto Class Doc Comment
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MdSettingsDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MdSettingsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'hardLineBreaksSegments' => 'bool',
        'preserveWhiteSpaces' => 'bool',
        'tagRegexp' => 'string',
        'customElements' => 'string',
        'ignoredBlockPrefixes' => 'string',
        'flavor' => 'string',
        'processJekyllFrontMatter' => 'bool',
        'extractCodeBlocks' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'hardLineBreaksSegments' => null,
        'preserveWhiteSpaces' => null,
        'tagRegexp' => null,
        'customElements' => null,
        'ignoredBlockPrefixes' => null,
        'flavor' => null,
        'processJekyllFrontMatter' => null,
        'extractCodeBlocks' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'hardLineBreaksSegments' => 'hardLineBreaksSegments',
        'preserveWhiteSpaces' => 'preserveWhiteSpaces',
        'tagRegexp' => 'tagRegexp',
        'customElements' => 'customElements',
        'ignoredBlockPrefixes' => 'ignoredBlockPrefixes',
        'flavor' => 'flavor',
        'processJekyllFrontMatter' => 'processJekyllFrontMatter',
        'extractCodeBlocks' => 'extractCodeBlocks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'hardLineBreaksSegments' => 'setHardLineBreaksSegments',
        'preserveWhiteSpaces' => 'setPreserveWhiteSpaces',
        'tagRegexp' => 'setTagRegexp',
        'customElements' => 'setCustomElements',
        'ignoredBlockPrefixes' => 'setIgnoredBlockPrefixes',
        'flavor' => 'setFlavor',
        'processJekyllFrontMatter' => 'setProcessJekyllFrontMatter',
        'extractCodeBlocks' => 'setExtractCodeBlocks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'hardLineBreaksSegments' => 'getHardLineBreaksSegments',
        'preserveWhiteSpaces' => 'getPreserveWhiteSpaces',
        'tagRegexp' => 'getTagRegexp',
        'customElements' => 'getCustomElements',
        'ignoredBlockPrefixes' => 'getIgnoredBlockPrefixes',
        'flavor' => 'getFlavor',
        'processJekyllFrontMatter' => 'getProcessJekyllFrontMatter',
        'extractCodeBlocks' => 'getExtractCodeBlocks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const FLAVOR_PLAIN = 'PLAIN';
    const FLAVOR_PHP = 'PHP';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFlavorAllowableValues()
    {
        return [
            self::FLAVOR_PLAIN,
            self::FLAVOR_PHP,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['hardLineBreaksSegments'] = isset($data['hardLineBreaksSegments']) ? $data['hardLineBreaksSegments'] : null;
        $this->container['preserveWhiteSpaces'] = isset($data['preserveWhiteSpaces']) ? $data['preserveWhiteSpaces'] : null;
        $this->container['tagRegexp'] = isset($data['tagRegexp']) ? $data['tagRegexp'] : null;
        $this->container['customElements'] = isset($data['customElements']) ? $data['customElements'] : null;
        $this->container['ignoredBlockPrefixes'] = isset($data['ignoredBlockPrefixes']) ? $data['ignoredBlockPrefixes'] : null;
        $this->container['flavor'] = isset($data['flavor']) ? $data['flavor'] : null;
        $this->container['processJekyllFrontMatter'] = isset($data['processJekyllFrontMatter']) ? $data['processJekyllFrontMatter'] : null;
        $this->container['extractCodeBlocks'] = isset($data['extractCodeBlocks']) ? $data['extractCodeBlocks'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getFlavorAllowableValues();
        if (!in_array($this->container['flavor'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'flavor', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowedValues = $this->getFlavorAllowableValues();
        if (!in_array($this->container['flavor'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets hardLineBreaksSegments
     *
     * @return bool
     */
    public function getHardLineBreaksSegments()
    {
        return $this->container['hardLineBreaksSegments'];
    }

    /**
     * Sets hardLineBreaksSegments
     *
     * @param bool $hardLineBreaksSegments default: true
     *
     * @return $this
     */
    public function setHardLineBreaksSegments($hardLineBreaksSegments)
    {
        $this->container['hardLineBreaksSegments'] = $hardLineBreaksSegments;

        return $this;
    }

    /**
     * Gets preserveWhiteSpaces
     *
     * @return bool
     */
    public function getPreserveWhiteSpaces()
    {
        return $this->container['preserveWhiteSpaces'];
    }

    /**
     * Sets preserveWhiteSpaces
     *
     * @param bool $preserveWhiteSpaces preserveWhiteSpaces
     *
     * @return $this
     */
    public function setPreserveWhiteSpaces($preserveWhiteSpaces)
    {
        $this->container['preserveWhiteSpaces'] = $preserveWhiteSpaces;

        return $this;
    }

    /**
     * Gets tagRegexp
     *
     * @return string
     */
    public function getTagRegexp()
    {
        return $this->container['tagRegexp'];
    }

    /**
     * Sets tagRegexp
     *
     * @param string $tagRegexp tagRegexp
     *
     * @return $this
     */
    public function setTagRegexp($tagRegexp)
    {
        $this->container['tagRegexp'] = $tagRegexp;

        return $this;
    }

    /**
     * Gets customElements
     *
     * @return string
     */
    public function getCustomElements()
    {
        return $this->container['customElements'];
    }

    /**
     * Sets customElements
     *
     * @param string $customElements customElements
     *
     * @return $this
     */
    public function setCustomElements($customElements)
    {
        $this->container['customElements'] = $customElements;

        return $this;
    }

    /**
     * Gets ignoredBlockPrefixes
     *
     * @return string
     */
    public function getIgnoredBlockPrefixes()
    {
        return $this->container['ignoredBlockPrefixes'];
    }

    /**
     * Sets ignoredBlockPrefixes
     *
     * @param string $ignoredBlockPrefixes ignoredBlockPrefixes
     *
     * @return $this
     */
    public function setIgnoredBlockPrefixes($ignoredBlockPrefixes)
    {
        $this->container['ignoredBlockPrefixes'] = $ignoredBlockPrefixes;

        return $this;
    }

    /**
     * Gets flavor
     *
     * @return string
     */
    public function getFlavor()
    {
        return $this->container['flavor'];
    }

    /**
     * Sets flavor
     *
     * @param string $flavor default: PLAIN
     *
     * @return $this
     */
    public function setFlavor($flavor)
    {
        $allowedValues = $this->getFlavorAllowableValues();
        if (!is_null($flavor) && !in_array($flavor, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'flavor', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['flavor'] = $flavor;

        return $this;
    }

    /**
     * Gets processJekyllFrontMatter
     *
     * @return bool
     */
    public function getProcessJekyllFrontMatter()
    {
        return $this->container['processJekyllFrontMatter'];
    }

    /**
     * Sets processJekyllFrontMatter
     *
     * @param bool $processJekyllFrontMatter processJekyllFrontMatter
     *
     * @return $this
     */
    public function setProcessJekyllFrontMatter($processJekyllFrontMatter)
    {
        $this->container['processJekyllFrontMatter'] = $processJekyllFrontMatter;

        return $this;
    }

    /**
     * Gets extractCodeBlocks
     *
     * @return bool
     */
    public function getExtractCodeBlocks()
    {
        return $this->container['extractCodeBlocks'];
    }

    /**
     * Sets extractCodeBlocks
     *
     * @param bool $extractCodeBlocks default: true
     *
     * @return $this
     */
    public function setExtractCodeBlocks($extractCodeBlocks)
    {
        $this->container['extractCodeBlocks'] = $extractCodeBlocks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


