<?php
/**
 * XlsSettingsDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Memsource\Model;

use \ArrayAccess;
use \Memsource\ObjectSerializer;

/**
 * XlsSettingsDto Class Doc Comment
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class XlsSettingsDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'XlsSettingsDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sheetNames' => 'bool',
        'hidden' => 'bool',
        'comments' => 'bool',
        'other' => 'bool',
        'cellFlow' => 'string',
        'htmlSubfilter' => 'bool',
        'tagRegexp' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sheetNames' => null,
        'hidden' => null,
        'comments' => null,
        'other' => null,
        'cellFlow' => null,
        'htmlSubfilter' => null,
        'tagRegexp' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sheetNames' => 'sheetNames',
        'hidden' => 'hidden',
        'comments' => 'comments',
        'other' => 'other',
        'cellFlow' => 'cellFlow',
        'htmlSubfilter' => 'htmlSubfilter',
        'tagRegexp' => 'tagRegexp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sheetNames' => 'setSheetNames',
        'hidden' => 'setHidden',
        'comments' => 'setComments',
        'other' => 'setOther',
        'cellFlow' => 'setCellFlow',
        'htmlSubfilter' => 'setHtmlSubfilter',
        'tagRegexp' => 'setTagRegexp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sheetNames' => 'getSheetNames',
        'hidden' => 'getHidden',
        'comments' => 'getComments',
        'other' => 'getOther',
        'cellFlow' => 'getCellFlow',
        'htmlSubfilter' => 'getHtmlSubfilter',
        'tagRegexp' => 'getTagRegexp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CELL_FLOW_DOWN_RIGHT = 'DownRight';
    const CELL_FLOW_RIGHT_DOWN = 'RightDown';
    const CELL_FLOW_DOWN_LEFT = 'DownLeft';
    const CELL_FLOW_LEFT_DOWN = 'LeftDown';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCellFlowAllowableValues()
    {
        return [
            self::CELL_FLOW_DOWN_RIGHT,
            self::CELL_FLOW_RIGHT_DOWN,
            self::CELL_FLOW_DOWN_LEFT,
            self::CELL_FLOW_LEFT_DOWN,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sheetNames'] = isset($data['sheetNames']) ? $data['sheetNames'] : null;
        $this->container['hidden'] = isset($data['hidden']) ? $data['hidden'] : null;
        $this->container['comments'] = isset($data['comments']) ? $data['comments'] : null;
        $this->container['other'] = isset($data['other']) ? $data['other'] : null;
        $this->container['cellFlow'] = isset($data['cellFlow']) ? $data['cellFlow'] : null;
        $this->container['htmlSubfilter'] = isset($data['htmlSubfilter']) ? $data['htmlSubfilter'] : null;
        $this->container['tagRegexp'] = isset($data['tagRegexp']) ? $data['tagRegexp'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCellFlowAllowableValues();
        if (!in_array($this->container['cellFlow'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'cellFlow', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowedValues = $this->getCellFlowAllowableValues();
        if (!in_array($this->container['cellFlow'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets sheetNames
     *
     * @return bool
     */
    public function getSheetNames()
    {
        return $this->container['sheetNames'];
    }

    /**
     * Sets sheetNames
     *
     * @param bool $sheetNames sheetNames
     *
     * @return $this
     */
    public function setSheetNames($sheetNames)
    {
        $this->container['sheetNames'] = $sheetNames;

        return $this;
    }

    /**
     * Gets hidden
     *
     * @return bool
     */
    public function getHidden()
    {
        return $this->container['hidden'];
    }

    /**
     * Sets hidden
     *
     * @param bool $hidden hidden
     *
     * @return $this
     */
    public function setHidden($hidden)
    {
        $this->container['hidden'] = $hidden;

        return $this;
    }

    /**
     * Gets comments
     *
     * @return bool
     */
    public function getComments()
    {
        return $this->container['comments'];
    }

    /**
     * Sets comments
     *
     * @param bool $comments comments
     *
     * @return $this
     */
    public function setComments($comments)
    {
        $this->container['comments'] = $comments;

        return $this;
    }

    /**
     * Gets other
     *
     * @return bool
     */
    public function getOther()
    {
        return $this->container['other'];
    }

    /**
     * Sets other
     *
     * @param bool $other other
     *
     * @return $this
     */
    public function setOther($other)
    {
        $this->container['other'] = $other;

        return $this;
    }

    /**
     * Gets cellFlow
     *
     * @return string
     */
    public function getCellFlow()
    {
        return $this->container['cellFlow'];
    }

    /**
     * Sets cellFlow
     *
     * @param string $cellFlow default: DownRight
     *
     * @return $this
     */
    public function setCellFlow($cellFlow)
    {
        $allowedValues = $this->getCellFlowAllowableValues();
        if (!is_null($cellFlow) && !in_array($cellFlow, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'cellFlow', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['cellFlow'] = $cellFlow;

        return $this;
    }

    /**
     * Gets htmlSubfilter
     *
     * @return bool
     */
    public function getHtmlSubfilter()
    {
        return $this->container['htmlSubfilter'];
    }

    /**
     * Sets htmlSubfilter
     *
     * @param bool $htmlSubfilter htmlSubfilter
     *
     * @return $this
     */
    public function setHtmlSubfilter($htmlSubfilter)
    {
        $this->container['htmlSubfilter'] = $htmlSubfilter;

        return $this;
    }

    /**
     * Gets tagRegexp
     *
     * @return string
     */
    public function getTagRegexp()
    {
        return $this->container['tagRegexp'];
    }

    /**
     * Sets tagRegexp
     *
     * @param string $tagRegexp tagRegexp
     *
     * @return $this
     */
    public function setTagRegexp($tagRegexp)
    {
        $this->container['tagRegexp'] = $tagRegexp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


