<?php
/**
 * CreateProjectDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Memsource;

/**
 * CreateProjectDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateProjectDto
/**
 * @package     Memsource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateProjectDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateProjectDto"
     */
    public function testCreateProjectDto()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "sourceLang"
     */
    public function testPropertySourceLang()
    {
    }

    /**
     * Test attribute "targetLangs"
     */
    public function testPropertyTargetLangs()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "businessUnit"
     */
    public function testPropertyBusinessUnit()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "subDomain"
     */
    public function testPropertySubDomain()
    {
    }

    /**
     * Test attribute "useDefaultProjectSettings"
     */
    public function testPropertyUseDefaultProjectSettings()
    {
    }

    /**
     * Test attribute "purchaseOrder"
     */
    public function testPropertyPurchaseOrder()
    {
    }

    /**
     * Test attribute "workflowSteps"
     */
    public function testPropertyWorkflowSteps()
    {
    }

    /**
     * Test attribute "dateDue"
     */
    public function testPropertyDateDue()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }
}
