<?php
/**
 * ExportByQueryDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Memsource;

/**
 * ExportByQueryDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description ExportByQueryDto
/**
 * @package     Memsource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExportByQueryDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExportByQueryDto"
     */
    public function testExportByQueryDto()
    {
    }

    /**
     * Test attribute "exportTargetLangs"
     */
    public function testPropertyExportTargetLangs()
    {
    }

    /**
     * Test attribute "queries"
     */
    public function testPropertyQueries()
    {
    }

    /**
     * Test attribute "queryLangs"
     */
    public function testPropertyQueryLangs()
    {
    }

    /**
     * Test attribute "createdAtMin"
     */
    public function testPropertyCreatedAtMin()
    {
    }

    /**
     * Test attribute "createdAtMax"
     */
    public function testPropertyCreatedAtMax()
    {
    }

    /**
     * Test attribute "modifiedAtMin"
     */
    public function testPropertyModifiedAtMin()
    {
    }

    /**
     * Test attribute "modifiedAtMax"
     */
    public function testPropertyModifiedAtMax()
    {
    }

    /**
     * Test attribute "createdBy"
     */
    public function testPropertyCreatedBy()
    {
    }

    /**
     * Test attribute "modifiedBy"
     */
    public function testPropertyModifiedBy()
    {
    }

    /**
     * Test attribute "filename"
     */
    public function testPropertyFilename()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "callbackUrl"
     */
    public function testPropertyCallbackUrl()
    {
    }
}
