<?php
/**
 * FileImportSettingsCreateDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Memsource;

/**
 * FileImportSettingsCreateDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description FileImportSettingsCreateDto
/**
 * @package     Memsource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileImportSettingsCreateDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FileImportSettingsCreateDto"
     */
    public function testFileImportSettingsCreateDto()
    {
    }

    /**
     * Test attribute "inputCharset"
     */
    public function testPropertyInputCharset()
    {
    }

    /**
     * Test attribute "outputCharset"
     */
    public function testPropertyOutputCharset()
    {
    }

    /**
     * Test attribute "zipCharset"
     */
    public function testPropertyZipCharset()
    {
    }

    /**
     * Test attribute "fileFormat"
     */
    public function testPropertyFileFormat()
    {
    }

    /**
     * Test attribute "targetLength"
     */
    public function testPropertyTargetLength()
    {
    }

    /**
     * Test attribute "targetLengthMax"
     */
    public function testPropertyTargetLengthMax()
    {
    }

    /**
     * Test attribute "targetLengthPercent"
     */
    public function testPropertyTargetLengthPercent()
    {
    }

    /**
     * Test attribute "targetLengthPercentValue"
     */
    public function testPropertyTargetLengthPercentValue()
    {
    }

    /**
     * Test attribute "segmentationRuleId"
     */
    public function testPropertySegmentationRuleId()
    {
    }

    /**
     * Test attribute "csv"
     */
    public function testPropertyCsv()
    {
    }

    /**
     * Test attribute "dita"
     */
    public function testPropertyDita()
    {
    }

    /**
     * Test attribute "docBook"
     */
    public function testPropertyDocBook()
    {
    }

    /**
     * Test attribute "doc"
     */
    public function testPropertyDoc()
    {
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
    }

    /**
     * Test attribute "idml"
     */
    public function testPropertyIdml()
    {
    }

    /**
     * Test attribute "json"
     */
    public function testPropertyJson()
    {
    }

    /**
     * Test attribute "mac"
     */
    public function testPropertyMac()
    {
    }

    /**
     * Test attribute "md"
     */
    public function testPropertyMd()
    {
    }

    /**
     * Test attribute "mif"
     */
    public function testPropertyMif()
    {
    }

    /**
     * Test attribute "multilingualXls"
     */
    public function testPropertyMultilingualXls()
    {
    }

    /**
     * Test attribute "multilingualXml"
     */
    public function testPropertyMultilingualXml()
    {
    }

    /**
     * Test attribute "pdf"
     */
    public function testPropertyPdf()
    {
    }

    /**
     * Test attribute "php"
     */
    public function testPropertyPhp()
    {
    }

    /**
     * Test attribute "po"
     */
    public function testPropertyPo()
    {
    }

    /**
     * Test attribute "ppt"
     */
    public function testPropertyPpt()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "psd"
     */
    public function testPropertyPsd()
    {
    }

    /**
     * Test attribute "quarkTag"
     */
    public function testPropertyQuarkTag()
    {
    }

    /**
     * Test attribute "resx"
     */
    public function testPropertyResx()
    {
    }

    /**
     * Test attribute "sdlXlf"
     */
    public function testPropertySdlXlf()
    {
    }

    /**
     * Test attribute "tmMatch"
     */
    public function testPropertyTmMatch()
    {
    }

    /**
     * Test attribute "ttx"
     */
    public function testPropertyTtx()
    {
    }

    /**
     * Test attribute "txt"
     */
    public function testPropertyTxt()
    {
    }

    /**
     * Test attribute "xlf2"
     */
    public function testPropertyXlf2()
    {
    }

    /**
     * Test attribute "xlf"
     */
    public function testPropertyXlf()
    {
    }

    /**
     * Test attribute "xls"
     */
    public function testPropertyXls()
    {
    }

    /**
     * Test attribute "xml"
     */
    public function testPropertyXml()
    {
    }

    /**
     * Test attribute "yaml"
     */
    public function testPropertyYaml()
    {
    }
}
