<?php
/**
 * MifSettingsDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Memsource;

/**
 * MifSettingsDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description MifSettingsDto
/**
 * @package     Memsource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MifSettingsDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MifSettingsDto"
     */
    public function testMifSettingsDto()
    {
    }

    /**
     * Test attribute "extractBodyPages"
     */
    public function testPropertyExtractBodyPages()
    {
    }

    /**
     * Test attribute "extractReferencePages"
     */
    public function testPropertyExtractReferencePages()
    {
    }

    /**
     * Test attribute "extractMasterPages"
     */
    public function testPropertyExtractMasterPages()
    {
    }

    /**
     * Test attribute "extractHiddenPages"
     */
    public function testPropertyExtractHiddenPages()
    {
    }

    /**
     * Test attribute "extractVariables"
     */
    public function testPropertyExtractVariables()
    {
    }

    /**
     * Test attribute "extractIndexMarkers"
     */
    public function testPropertyExtractIndexMarkers()
    {
    }

    /**
     * Test attribute "extractLinks"
     */
    public function testPropertyExtractLinks()
    {
    }

    /**
     * Test attribute "extractXRefDef"
     */
    public function testPropertyExtractXRefDef()
    {
    }

    /**
     * Test attribute "extractPgfNumFormat"
     */
    public function testPropertyExtractPgfNumFormat()
    {
    }

    /**
     * Test attribute "extractCustomReferencePages"
     */
    public function testPropertyExtractCustomReferencePages()
    {
    }

    /**
     * Test attribute "extractDefaultReferencePages"
     */
    public function testPropertyExtractDefaultReferencePages()
    {
    }

    /**
     * Test attribute "extractUsedVariables"
     */
    public function testPropertyExtractUsedVariables()
    {
    }

    /**
     * Test attribute "extractHiddenCondText"
     */
    public function testPropertyExtractHiddenCondText()
    {
    }

    /**
     * Test attribute "extractUsedXRefDef"
     */
    public function testPropertyExtractUsedXRefDef()
    {
    }

    /**
     * Test attribute "extractUsedPgfNumFormat"
     */
    public function testPropertyExtractUsedPgfNumFormat()
    {
    }
}
