<?php
/**
 * Xlf2SettingsDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Memsource;

/**
 * Xlf2SettingsDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description Xlf2SettingsDto
/**
 * @package     Memsource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Xlf2SettingsDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Xlf2SettingsDto"
     */
    public function testXlf2SettingsDto()
    {
    }

    /**
     * Test attribute "importNotes"
     */
    public function testPropertyImportNotes()
    {
    }

    /**
     * Test attribute "saveConfirmedSegments"
     */
    public function testPropertySaveConfirmedSegments()
    {
    }

    /**
     * Test attribute "segmentation"
     */
    public function testPropertySegmentation()
    {
    }

    /**
     * Test attribute "lineBreakTags"
     */
    public function testPropertyLineBreakTags()
    {
    }

    /**
     * Test attribute "preserveWhitespace"
     */
    public function testPropertyPreserveWhitespace()
    {
    }

    /**
     * Test attribute "copySourceToTargetIfNotImported"
     */
    public function testPropertyCopySourceToTargetIfNotImported()
    {
    }

    /**
     * Test attribute "respectTranslateAttr"
     */
    public function testPropertyRespectTranslateAttr()
    {
    }

    /**
     * Test attribute "skipImportRules"
     */
    public function testPropertySkipImportRules()
    {
    }

    /**
     * Test attribute "importAsConfirmedRules"
     */
    public function testPropertyImportAsConfirmedRules()
    {
    }

    /**
     * Test attribute "importAsLockedRules"
     */
    public function testPropertyImportAsLockedRules()
    {
    }

    /**
     * Test attribute "exportAttrsWhenConfirmedAndLocked"
     */
    public function testPropertyExportAttrsWhenConfirmedAndLocked()
    {
    }

    /**
     * Test attribute "exportAttrsWhenConfirmedAndNotLocked"
     */
    public function testPropertyExportAttrsWhenConfirmedAndNotLocked()
    {
    }

    /**
     * Test attribute "exportAttrsWhenNotConfirmedAndLocked"
     */
    public function testPropertyExportAttrsWhenNotConfirmedAndLocked()
    {
    }

    /**
     * Test attribute "exportAttrsWhenNotConfirmedAndNotLocked"
     */
    public function testPropertyExportAttrsWhenNotConfirmedAndNotLocked()
    {
    }

    /**
     * Test attribute "contextKeyXPath"
     */
    public function testPropertyContextKeyXPath()
    {
    }
}
