<?php
/**
 * SegmentationRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Memsource REST API
 *
 * Welcome to Memsource's API documentation. To view our legacy APIs please [visit our documentation](https://wiki.memsource.com/wiki/Memsource_API) and for more information about our new APIs, [visit our blog](https://www.memsource.com/blog/2017/10/24/introducing-rest-apis-qa-with-the-memsource-api-team/).    If you have any questions, please contact [Memsource Support](<mailto:support@memsource.com>).
 *
 * OpenAPI spec version: All
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Memsource;

use \Memsource\Configuration;
use \Memsource\ApiException;
use \Memsource\ObjectSerializer;

/**
 * SegmentationRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Memsource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SegmentationRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSegmentationRule
     *
     * Create segmentation rule.
     *
     */
    public function testCreateSegmentationRule()
    {
    }

    /**
     * Test case for deletesSegmentationRule
     *
     * Delete segmentation rule.
     *
     */
    public function testDeletesSegmentationRule()
    {
    }

    /**
     * Test case for getListOfSegmentationRules
     *
     * List segmentation rules.
     *
     */
    public function testGetListOfSegmentationRules()
    {
    }

    /**
     * Test case for getSegmentationRule
     *
     * Get segmentation rule.
     *
     */
    public function testGetSegmentationRule()
    {
    }

    /**
     * Test case for updatesSegmentationRule
     *
     * Edit segmentation rule.
     *
     */
    public function testUpdatesSegmentationRule()
    {
    }
}
